Repository Y-Foundry-Dao/yfd-docs, pull requests merged in 2022-11, with the labels that each got.

#14 File & image Standards
  docs/_contribute/file-convention.md
Labels: documentation, enhancement

#15 vault proposal pages
  docs/_develop/contractMessages/contracts/vaultProposal/proposalExecute.md
  docs/_develop/contractMessages/contracts/vaultProposal/proposalMessages.md
  docs/_develop/contractMessages/contracts/vaultProposal/proposalQuery.md
Labels: enhancement

#18 Close liquid syntax tag so jekyll can build
  docs/_develop/contractMessages/contracts/proposal/proposalExecute.md
Labels: bug
